# Generated by Django 5.0.7 on 2024-10-04 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='reviews_count',
        ),
    ]
