# Generated by Django 5.0.7 on 2024-10-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0004_remove_dress_reviews_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='additional_images',
        ),
    ]
