# Generated by Django 5.0.7 on 2024-10-04 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0005_remove_dress_additional_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dress_images/')),
                ('dress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerceapp.dress')),
            ],
        ),
    ]
