# Generated by Django 5.0.7 on 2024-10-04 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0006_dressimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='add_img1',
            field=models.ImageField(null=True, upload_to='additional_dresses/'),
        ),
        migrations.AddField(
            model_name='dress',
            name='add_img2',
            field=models.ImageField(null=True, upload_to='additional_dresses/'),
        ),
        migrations.AddField(
            model_name='dress',
            name='add_img3',
            field=models.ImageField(null=True, upload_to='additional_dresses/'),
        ),
        migrations.DeleteModel(
            name='DressImage',
        ),
    ]
