# Generated by Django 5.0.7 on 2024-10-04 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0007_dress_add_img1_dress_add_img2_dress_add_img3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='category',
            field=models.CharField(choices=[('BOHEMIAN_OUTFIT', 'Bohemian Outfit'), ('BOHO_MEN_STYLE', 'Boho Men Style'), ('COACHELLA_OUTFIT', 'Coachella Outfit'), ('BOHO_CHIC_MEN', 'Boho Chic Men'), ('MENS_RABE_OUTFIT', "Men's Rabe Outfit"), ('BOHO_HIPPY', 'Boho Hippie')], max_length=50),
        ),
    ]
