# Generated by Django 5.0.7 on 2024-10-04 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0008_alter_dress_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dress',
            name='occasion',
        ),
    ]
