# Generated by Django 5.0.7 on 2024-10-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0009_remove_dress_occasion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dress',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
