# Generated by Django 5.0.7 on 2024-10-19 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0010_dress_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dress',
            name='size',
            field=models.CharField(choices=[('small', 'S'), ('medium', 'M'), ('large', 'L'), ('xlarge', 'XL'), ('xxlarge', 'XXL')], max_length=50),
        ),
    ]
