# Generated by Django 5.0.7 on 2024-10-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0014_user_country_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
