# Generated by Django 5.0.7 on 2024-10-21 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0015_user_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
